version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '00:25'
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    target-branch: updates/deps
    reviewers:
      - mheob
    assignees:
      - mheob
